### ISSUE TITLE
問題名の 20 バイト目が char boundary でないと submit 後に panic する

### ISSUE THREAD

**Issue by MiSawa** [tanakh/cargo-atcoder#6]
例えば [A - 2 倍チェック / Is It a Number?](https://atcoder.jp/contests/past201912-open/tasks/past201912_a) でこの現象が起きます.
[以下の行](https://github.com/tanakh/cargo-atcoder/blob/master/src/main.rs#L799) で最初の 20 bytes を取ろうとしているのが原因のようです.
```rust
                    pb.set_prefix(&format!(
                        "{} | {:20} |",
                        DateTime::<Local>::from(result.date).format("%Y-%m-%d %H:%M:%S"),
                        &result.problem_name[0..min(20, result.problem_name.len())],
                    ));
```

```
Fetching submission result...
thread 'main' panicked at 'byte index 20 is not a char boundary; it is inside 'ク' (bytes 18..21) of `A - 2 倍チェック / Is It a Number?`', src/libcore/str/mod.rs:2068:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::str::slice_error_fail
             at src/libcore/str/mod.rs:0
  15: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}
  16: alloc::collections::btree::map::Entry<K,V>::or_insert_with
  17: cargo_atcoder::watch_submission_status::{{closure}}::{{closure}}
  18: tokio::task::core::Core<T>::poll
  19: std::panicking::try::do_call
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  21: tokio::task::harness::Harness<T,S>::poll
  22: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  23: tokio::runtime::context::enter
  24: tokio::runtime::handle::Handle::enter
  25: cargo_atcoder::main
  26: std::rt::lang_start::{{closure}}
  27: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  28: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  29: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  30: std::panicking::try
             at src/libstd/panicking.rs:265
  31: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  32: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  33: main
  34: __libc_start_main
  35: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
^C
[1]    29112 interrupt  cargo atcoder submit a
```

**Comment by tanakh** [comment]
ご報告ありがとうございます。修正されましたでしょうか。

**Comment by MiSawa** [comment]
`past201912_a` で、無事提出でき、 panic せず終了することを確認しました。
対応ありがとうございました！
